# GitHub Action to publish mdi-desktop-app _draft_ releases
# must manually make the release public on GitHub!!
name: "Electron Builder"
on:
  push:
    paths:
      - 'package.json' # only release when version changes
  workflow_dispatch: # also allow manual execution of Action

# give electron-builder permission to publish releases
env:
  GH_TOKEN: ${{ secrets.github_token }}

# setup OS environments
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest] # , ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # install node modules
      - run: npm clean-install

      # # publish Windows release
      # - name: Run npm run release (Windows)
      #   if: runner.os == 'Windows'
      #   env: 
      #     CSC_LINK: ${{ secrets.win_csc_link }}
      #     CSC_KEY_PASSWORD: ${{ secrets.win_csc_key_password }}
      #   run: npm run release

      # publish Mac release
      - name: Run npm run release (macOS)
        if: runner.os == 'macOS'
        env: 
          CSC_LINK: ${{ secrets.mac_csc_link }} # for signing
          CSC_KEY_PASSWORD: ${{ secrets.mac_csc_key_password }}
          APPLE_ID: ${{ secrets.apple_id }} # for notarization
          APPLE_ID_PASSWORD: ${{ secrets.apple_id_password }}
          APPLE_TEAM_ID: ${{ secrets.apple_team_id }}
        run: npm run release
        continue-on-error: true

      - run: pwd
      - run: ls -lah
