name: "Electron Builder"
on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest  #${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [macos-latest, windows-latest] # , ubuntu-latest
    steps:
      - name: repository checkout
        uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      - name: ls -l
        run: ls -l
      - name: npm install
        run: npm install
      - name: ls -l node_modules
        run: ls -l node_modules
      - run: npm run dist
      # - uses: samuelmeuli/action-electron-builder@v1.6.0
      #   with:
      #     github_token: ${{ secrets.github_token }}
      #     release: ${{ startsWith(github.ref, 'refs/tags/v') }}
