name: "Electron Builder"
on:
  # release:
  #   types: [published]
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.github_token }}
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest] # , ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - name: Run npm run ci (Windows)
        if: runner.os == 'Windows'
        env: 
          XYZ: ${{ runner.os }}
        run: npm run ci
      - name: Run npm run ci (macOS)
        if: runner.os == 'macOS'
        env: 
          XYZ: ${{ runner.os }}
        run: npm run ci

# CSC_LINK, CSC_KEY_PASSWORD
# ${{ secrets.win_certs }}
# ${{ secrets.win_certs_password }}
# ${{ secrets.mac_certs }}
# ${{ secrets.mac_certs_password }}
