name: "Electron Builder"
on:
  push:
    paths:
      - 'package.json' # only release when version changes
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.github_token }}
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest] # , ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm clean-install
      # - run: npm run build # if you need it
      - name: Run npm run release (Windows)
        if: runner.os == 'Windows'
        # env: 
          # CSC_LINK: ${{ secrets.win_certs }}
          # CSC_KEY_PASSWORD: ${{ secrets.win_certs_password }}
        run: npm run release
      - name: Run npm run release (macOS)
        if: runner.os == 'macOS'
        # env: 
          # CSC_LINK: ${{ secrets.mac_certs }}
          # CSC_KEY_PASSWORD: ${{ secrets.mac_certs_password }}
        run: npm run release
